# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: webcam_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'webcam_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14webcam_service.proto\"!\n\x0cImageRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"#\n\rImageResponse\x12\x12\n\nimage_data\x18\x04 \x01(\x0c\x32t\n\rWebcamService\x12/\n\x0c\x43\x61ptureImage\x12\r.ImageRequest\x1a\x0e.ImageResponse\"\x00\x12\x32\n\x0bImageStream\x12\r.ImageRequest\x1a\x0e.ImageResponse\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'webcam_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=24
  _globals['_IMAGEREQUEST']._serialized_end=57
  _globals['_IMAGERESPONSE']._serialized_start=59
  _globals['_IMAGERESPONSE']._serialized_end=94
  _globals['_WEBCAMSERVICE']._serialized_start=96
  _globals['_WEBCAMSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
