# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import webcam_service_pb2 as webcam__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in webcam_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WebcamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartStreaming = channel.unary_unary(
                '/WebcamService/StartStreaming',
                request_serializer=webcam__service__pb2.StartRequest.SerializeToString,
                response_deserializer=webcam__service__pb2.StartResponse.FromString,
                _registered_method=True)
        self.StopStreaming = channel.unary_unary(
                '/WebcamService/StopStreaming',
                request_serializer=webcam__service__pb2.StopRequest.SerializeToString,
                response_deserializer=webcam__service__pb2.StopResponse.FromString,
                _registered_method=True)
        self.CaptureImage = channel.unary_unary(
                '/WebcamService/CaptureImage',
                request_serializer=webcam__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=webcam__service__pb2.ImageResponse.FromString,
                _registered_method=True)
        self.ImageStream = channel.stream_stream(
                '/WebcamService/ImageStream',
                request_serializer=webcam__service__pb2.ImageRequest.SerializeToString,
                response_deserializer=webcam__service__pb2.ImageResponse.FromString,
                _registered_method=True)


class WebcamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WebcamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStreaming,
                    request_deserializer=webcam__service__pb2.StartRequest.FromString,
                    response_serializer=webcam__service__pb2.StartResponse.SerializeToString,
            ),
            'StopStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreaming,
                    request_deserializer=webcam__service__pb2.StopRequest.FromString,
                    response_serializer=webcam__service__pb2.StopResponse.SerializeToString,
            ),
            'CaptureImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureImage,
                    request_deserializer=webcam__service__pb2.ImageRequest.FromString,
                    response_serializer=webcam__service__pb2.ImageResponse.SerializeToString,
            ),
            'ImageStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ImageStream,
                    request_deserializer=webcam__service__pb2.ImageRequest.FromString,
                    response_serializer=webcam__service__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WebcamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('WebcamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WebcamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebcamService/StartStreaming',
            webcam__service__pb2.StartRequest.SerializeToString,
            webcam__service__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebcamService/StopStreaming',
            webcam__service__pb2.StopRequest.SerializeToString,
            webcam__service__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/WebcamService/CaptureImage',
            webcam__service__pb2.ImageRequest.SerializeToString,
            webcam__service__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/WebcamService/ImageStream',
            webcam__service__pb2.ImageRequest.SerializeToString,
            webcam__service__pb2.ImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
